---
# tasks file for lighthouse-role
- name: Install Lighthouse
  git:
    repo: "{{ lighthouse_repo }}"
    version: master
    dest: "{{ lighthouse_dir_location }}"
- name: Lighthouse config
  become: true
  template:
    src: ighthouse.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: "0644"
  notify: Restart nginx
